fix Obj-C file extension in project.pbxproj
react-native-community/bob pull request #76
Opened 2020-08-06 12:10 UTC by Simek

# Summary

Currently when creating Native Module package for iOS the invalid Objective-C implementation file extension (`.mm`) is provided in `project.pbxproj`. This causes the inability to open and edit the package [`.m` file](https://github.com/react-native-community/bob/tree/master/templates/objc-library/ios) in XCode.

This PR fixes that issue simply by replacing the incorrect file extension with the correct one.

## Test Plan

After generating the project with the change I can open implementation code in the XCode.

### What's required for testing (prerequisites)?

XCode!

### What are the steps to reproduce (after prerequisites)?

Generate iOS Native Project and try to open main file in XCode.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ❌     |

## Checklist

- [ ] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

2020-09-30 16:26 UTC, satya164 requested changes
Hey! Thanks a lot for the PR and sorry for the late review. We need `mm` extension for C++ modules afaik. Can you add a conditional to have `mm` for C++ module and `m` for rest like we do for swift?

2020-09-30 18:39 UTC, Simek commented
> Hey! Thanks a lot for the PR and sorry for the late review. We need `mm` extension for C++ modules afaik. Can you add a conditional to have `mm` for C++ module and `m` for rest like we do for swift?

@satya164 Thank you for the review! I have a stashed changeset with review changes ready, but I want to ask one question before I push it: Dose the Swift project requires `.m` files too? It is not obvious from the current file, because `.m` files are present in some swift conditionals but not all of them (PBXBuildFile section do not include source `.m` file for example).

2020-09-30 18:44 UTC, satya164 commented
I had received a PR for adding Swift and C++ so I am not 100% sure, but if I understand correctly, for both Swift and Obj-C, we need `.m` and for C++ we need `.mm` :)

2020-09-30 19:01 UTC, Simek commented
I hope that I made the correct changes. I have tried to clean up the logic a bit by merging conditionals (so now there are always three branches: CPP, Swift and rest). Let me know what do you think and if updates are correct in the first place. 🙂

2020-10-01 11:01 UTC, satya164 approved these changes

2020-10-01 11:01 UTC, merged